parameters:
  - name: "apiAppName"
    type: string
  - name: "packageLocation"
    type: string
  - name: "azureSubscriptionId"
    type: string
  - name: "serviceConnection"
    type: string

steps:
  - download: current
    artifact: WebApp
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: "Resource Group"
      azureResourceManagerConnection: "${{ parameters.serviceConnection }}"
      subscriptionId: "${{ parameters.azureSubscriptionId }}"
      action: "Create Or Update Resource Group"
      resourceGroupName: "MyAppDeleteMeLateGroup"
      location: "UK South"
      templateLocation: "Linked artifact"
      csmFile: "$(Pipeline.Workspace)/WebApp/IaC/WebAPI.json"
      csmParametersFile: "$(Pipeline.Workspace)/WebApp/IaC/WebAPI.parameters.json"
      overrideParameters: "-apiAppName ${{ parameters.apiAppName }}"
      deploymentMode: "Incremental"
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: "AzureRM"
      azureSubscription: "${{ parameters.serviceConnection }}"
      appType: "webAppLinux"
      WebAppName: ${{ parameters.apiAppName }}
      packageForLinux: ${{ parameters.packageLocation }}
      RuntimeStack: "DOTNETCORE|5.0"
